### ISSUE TITLE
decide about spaces after/before exclamation mark

### ISSUE THREAD

**Issue by rdeutz** [joomla/coding-standards#113]
In this PR https://github.com/joomla/joomla-cms/pull/7292/files#r33676349 the question raised if we should allow or deny a space after a exclamation mark in a condition. There is a longer discussion about this here: https://github.com/php-fig/fig-standards/issues/102 and https://github.com/php-fig/fig-standards/issues/165. 

so how should we write it:

a) 

``` php
    if ( ! condition) 
```

Space before and after the exclamation mark

or 

b) 

``` php
    if (!condition)
```

Happy commenting :-)

**Comment by zero-24** [comment]
Personaly and for me: `if (!condition)` looks cleaner and it is the current standard* that we use in the most CMS Code.

*Ok no official standard but the current used one. :smile:

**Comment by roland-d** [comment]
I choose b.

**Comment by btoplak** [comment]
I use (b) for years, I don't have problems spotting it, and I'd say it's defacto unwritten PHP standard. And prevails throughout the J! Core code. 

As said in the original ticket - if one wants to emphasize the check, use `($var === false)` or `(false === $var)`

So, **definitely (b)** as a official standard.

**Comment by asika32764** [comment]
(b) +1

**Comment by dongilbert** [comment]
C) if (! $var)

**Comment by photodude** [comment]
:+1:  (b)

**Comment by virgofx** [comment]
C) `if (! $var)

**Comment by asika32764** [comment]
B, C +1

**Comment by elkuku** [comment]
C

Simon Asika <notifications@github.com> schrieb am Mi., 22. Juli 2015 10:09:

**Comment by photodude** [comment]
There is nothing that I can see in the [PSR-2 standard](http://www.php-fig.org/psr/psr-2/) or in the [proposed PSR-12 standard](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) in relation to this code style item. 

This is one of the many cases where PSR-2 and the future PSR-12 does not cover things we would like to enforce.

**Comment by rdeutz** [comment]
seems most people like b, closing it
