### ISSUE TITLE
CamelCase enforcement in namespaced classes

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#117]
From what I remember, part of our camel case rule with class names came from how `JLoader` in the CMS is designed and how it splits classes based on camel casing to align to the filesystem; it couldn't cope with multiple uppercase letters.  As our namespaced code is following PSR-4 standards, this is less of an issue.  So, throwing the idea around, IMO we have a couple of options for how to manage that.

- Continue enforcement of the camel case rule
- Allow non-camel cased class and namespaces

Technically neither one is an issue, it's probably more of a consistency thing than anything.  But, with allowing the non- option, you can represent a proper name correctly and not impose styling rules on them (i.e. `Joomla\Cache\XCache` versus `Joomla\Cache\Xcache` or `Joomla\GitHub\GitHub` versus `Joomla\Github\Github`).

Thoughts?

//cc @nonumber

**Comment by photodude** [comment]
Personally I'm not a fan of how the current camelCase rules get enforced. Especially the issues it has with not being able to cope with multiple uppercase letters. Or no allowing the first letter to be capitalized. 

I agree it's a consistency thing, and generally I think the camelCase enforcement is better than no enforcement in the naming scheme for classes, namespaces, methods, variables, etc.

My preference is for things like `Joomla\Cache\XCache` and `Joomla\GitHub\GitHub`

**Comment by nonumber** [comment]
I told myself not to get involved with discussions on the how and why of things.
But my 2 cents anyway.

I don't really care what rules are made. I'm just going through the code trying yo get things in line with any rules/guidelines that have been made.

My issue with allowing ```Joomla\Cache\XCache``` and ```Joomla\GitHub\GitHub``` is that it doesn't follow any rule. If you allow that, then why not allow ```JHTML```? We all changed that to ```JHtml```, ```JUri``, etc.
What would you do with things like ```iPad``? Like ```passiPadChecks``` vs ```passIpadChecks```.
If we drop the rule of only using capitals to split the different parts/words in the class/method names, then why use capitals at all. I know, I know, for readability.
But having no rule in place seems like a messy road. And the only logical rule I see is what is already stated here: http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md
> Class names should always begin with an uppercase letter and be written in CamelCase even if using traditionally uppercase acronyms (such as XML, HTML).

So essentially, you just lowercase everything, and then uppercase every letter that is prepended with a space (if written as normal sentence):
```String URL Unicode slug``` => ```string url unicode slug``` => ```StringUrlUnicodeSlug```
```J(oomla) Log Logger W3C Inspector``` => ```j log logger w3c inspector``` => ```JLogLoggerW3cInspector```
```Pass iPad checks``` => ```pass ipad checks``` => ```PassIpadChecks```
```XCache``` => ```xcache``` => ```Xcache```
```GitHub``` => ```github``` => ```Github```
