### ISSUE TITLE
Blank line between do/while?

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#126]
https://github.com/joomla-framework/filter/commit/a303f04a8b87ed798f7fcf55a6501d493f1f466b fixed a PHPCS issue.  The examples in http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md show a blank line between do/while shouldn't be needed.  Bad sniff or bad docs?

**Comment by photodude** [comment]
I would say bad sniff. do/while should be grouped like if/elseif/else
Issue is likely in the [ControlStructureSpacingSniff](https://github.com/joomla/coding-standards/blob/master/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php) or in the [ControlSignatureSniff](https://github.com/joomla/coding-standards/blob/master/Sniffs/ControlStructures/ControlSignatureSniff.php)

**Comment by mbabker** [comment]
https://github.com/joomla/coding-standards/blob/master/Sniffs/ControlStructures/ControlSignatureSniff.php#L60

It probably needs a pattern for do/while like the patterns above for if/elseif/else.  At least that's my first guess.

**Comment by photodude** [comment]
Seems reasonable, I would expect a pattern like this `'doEOL...{...}EOL...while (...)EOL...{EOL',`
I'll see if I can test something to verify that as being correct before submitting a PR
