### ISSUE TITLE
Bad sniff for parenthesis

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#130]
Getting the following error from the noted sniff:

```xml
<error line="147" column="3" severity="error" message="&quot;echo&quot; is a statement not a function; no parentheses are required" source="Joomla.Functions.StatementNotFunction.BracketsNotRequired"/>
```

The line in question (indentions left in place as exists in the source file):

```php
		echo (new JLayoutFile('install.result', JPATH_ADMINISTRATOR . '/components/com_podcastmanager/layouts'))->render(
			[
				'results' => $results, 'enabled' => $enabled
			]
		)
```

**Comment by photodude** [comment]
Is this a short array definition issue? 

I assume the source should look something like this, if it was including php5.3 support.
```
echo (new JLayoutFile('install.result', JPATH_ADMINISTRATOR . '/components/com_podcastmanager/layouts'))->render(
            array(
                     'results' => $results, 'enabled' => $enabled
            )
        )
```
The sniffs are currently (and in the phpcs2 draft) rejecting short array use as to maintain compatibility with Joomla projects still supporting php5.3 (Oh the things we could do if php5.3 was truly dead and not supported by Joomla projects)

**Comment by mbabker** [comment]
Changed it to run with full array syntax and the same error.

https://github.com/joomla/coding-standards/blob/master/Sniffs/Functions/StatementNotFunctionSniff.php

That sniff looks for the next token after one of the registered tokens and if it's an open parenthesis it raises an error.  So it won't accept PHP 5.4 syntax in this context.

**Comment by photodude** [comment]
Looking at the [source pear sniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/1.5/CodeSniffer/Standards/PEAR/Sniffs/Files/IncludingFileSniff.php), we added the tokens T_CLONE, and T_ECHO 
on echo is where I think it's throwing the error
Since [echo is not actually a function (it is a language construct)](http://php.net/manual/en/function.echo.php) the brackets are not required. but I'm not sure about echo 's behavior when followed immediately by new...

If I follow the Brackets right I think there is a misplaced one before the render call that should be at the end
```
echo (new JLayoutFile('install.result', JPATH_ADMINISTRATOR . '/components/com_podcastmanager/layouts')->render(
            array(
                     'results' => $results,
                     'enabled' => $enabled,
            )
        ))
```

Which would follow the format
```
$layout = new JLayoutFile('install.result', JPATH_ADMINISTRATOR . '/components/com_podcastmanager/layouts');
echo $layout->render(array('results' => $results, 'enabled' => $enabled,));
```

**Comment by mbabker** [comment]
That looks about right at a quick glance.  Basically, a sequence of `T_ECHO` `T_OPEN_PARENTHESIS` `T_NEW` should be allowed but right now the sniffer is groaning because of the `T_OPEN_PARENTHESIS` being present.

**Comment by photodude** [comment]
So we need to decide if echo can be allowed to use parenthesis. if yes, then that token should be removed from the sniff.

**Comment by mbabker** [comment]
I personally don't care either way as long as it allows PHP 5.4 syntax.  I get Joomla still supports 5.3 code but that shouldn't force us who aren't to write code resembling it.  If that means echo in general allows `echo (T_WHATEVER);` statements as a side effect I guess we'll have to accept it.

**Comment by photodude** [comment]
Looking deeper at the sniff, Short array is a separate question enforced by other sniffs. (sorry, I shot off the cuff with my first response assuming the short array was the cause). 
I think in the phpcs2 draft it's a question of Generic.Arrays.DisallowShortArraySyntax as an included or excluded sniff. 

For this error it's the specific to the `T_ECHO` token in the sniff. We remove that token we then get `echo (T_WHATEVER);` statements being allowed.

**Comment by mbabker** [comment]
Honestly, we're probably better off removing it.  Between the `T_ECHO` `T_OPEN_PARENTHESIS` `T_NEW` sequence and echoing a typecast object (`echo (int) $object->getCount();`) it might be more trouble than it's worth to enforce it.

**Comment by photodude** [comment]
Fixed in the PHPCS2 branch as well.
