### ISSUE TITLE
Operator Spacing Sniff Not Ignore Minus Operator in Conditional Statements

### ISSUE THREAD

**Issue by deminy** [joomla/coding-standards#15]
``` php
$query->bind(':' . count($values), $values[$index], self::getType($v), is_string($v) ? strlen($v) : -1);
```

Above code throws out following error when running PHPCS using the Joomla coding standards:

**Expected 1 space after "-"; 0 found**

A temporary solution is to change the code to:

``` php
$query->bind(':' . count($values), $values[$index], self::getType($v), is_string($v) ? strlen($v) : (-1));
```

A previous fix ( http://drupal.org/node/1759346 ) can be used to validate following code properly:

``` php
$a = true ? -1 : 1;
```

However, the fix doesn't work for following code:

``` php
$a = true ? 1 : -1;
```

**Comment by photodude** [comment]
I believe this is fixed in the PHPCS-2 branch. I'll double check later today.

**Comment by photodude** [comment]
I can confirm that this issue is fixed in the PHPCS-2 branch, as such this issue can be closed.
