### ISSUE TITLE
editor standards

### ISSUE THREAD

**Issue by N6REJ** [joomla/coding-standards#161]
I recall there being a set of standards for the IDE editor such as tab vs spaces 
![image](https://cloud.githubusercontent.com/assets/1850089/23121510/4e3dddc2-f726-11e6-907e-4474b6b07995.png)
but I can't seem to find any documentation on it anymore... Might be a good thing to add here.

**Comment by mbabker** [comment]
It's the last thing noted in the README, and all that stuff is in the IDE folder in the repo.
