### ISSUE TITLE
Make the 1.x branch installable through Composer

### ISSUE THREAD

**Issue by photodude** [joomla/coding-standards#171]
Efforts required to make the 1.x branch installable through Composer are needed as per the "Preparing for PHPCS 2.x Support" post https://developer.joomla.org/news/673-preparing-for-phpcs-2-x-support.html

**Comment by mbabker** [comment]
Shooting from the hip, we should be good having a composer.json file on the branch.  Then it's just ensuring there are good install instructions.

We probably won't tag a release off of it so the instructions would be to use the 1.x branch direct instead of using a version tag as normal.

**Comment by photodude** [comment]
Also shooting from the hip, we likely need to change the folder structure to match the master 2.x branch.

**Comment by photodude** [comment]
Closing as this "enhancement" has little to no value in 2019. Feel free to reopen or recreate if you have a different opinion.
