### ISSUE TITLE
Link to IDE is broken

### ISSUE THREAD

**Issue by uglyeoin** [joomla/coding-standards#172]
https://github.com/joomla/coding-standards at the bottom of this page is a link to

https://github.com/joomla/coding-standards/tree/master/IDE

It 404s

**Comment by mbabker** [comment]
@wilsonge @photodude Something to pull over from the 1.x branch.

**Comment by wilsonge** [comment]
I've fixed the link to the new location. @photodude I'm unsure if the files are still up to date with the new 2.x master branch tho :/

**Comment by uglyeoin** [comment]
It's no longer a link George, can you make it a link please

**Comment by photodude** [comment]
I believe the IDE files use the IDE code formaters. They likely need review to see if they are correct according to the current versions of the respective IDEs.

**Comment by photodude** [comment]
There is a sub issue question here... should the `IDE` files be in the `Joomla` folder or at the root like the `manual`?

**Comment by photodude** [comment]
This can be closed, the link has been fixed.
