### ISSUE TITLE
[alpha] Composer install fails

### ISSUE THREAD

**Issue by photodude** [joomla/coding-standards#182]
I've been trying to run the alpha install on the Joomla CMS. I added it to the [require-dev section](https://github.com/photodude/joomla-cms/blob/patch-9/composer.json) of the composer file, and since this is a testing run I've removed the lock file.

```php
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package joomla/coding-standards ~2.0 is satisfiable by joomla/coding-standards[2.0.0-alpha] but these conflict with your requirements or minimum-stability.
```

seems something is wrong in the composer file setup for the package.

**Comment by mbabker** [comment]
You need to use `~2.0@alpha` as your version constraint.  The CMS is set up to by default require stable packages, there isn't a stable 2.0 tag.

**Comment by photodude** [comment]
Thank you. That worked.

**Comment by photodude** [comment]
looks like the scripts section is failing to install the standard into the phpcs folder

**Comment by photodude** [comment]
seems we have the wrong path for the `--config-set installed_paths ../../..` in the post install

**Comment by photodude** [comment]
I've been told I misunderstand how the scripts portion of composer works. Apparently, it only works from a root package. So it works in the context of testing the package but not in the context of installing it as a dependency in a project. 

See 
- https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-
- https://getcomposer.org/doc/04-schema.md#root-package

We will need to update our documentation on use to explain how to use the `phpcs --config-set installed_paths /path/to/joomla-coding-standards`
