### ISSUE TITLE
Menu Item resets menu on save and new

### ISSUE THREAD

**Issue by tonypartridge** [joomla/coding-standards#190]
When select a menu and then new item the menu is pre-selected within the menu, this is great and speeds up development. 

When you click save and new, you still expect the menu you have previously selected / are in to be used. But instead it reverts to the menu block with the default menu item in. In my case Main Menu.

**Comment by zero-24** [comment]
Is this a issue with the coding standards? Or with the CMS?

**Comment by tonypartridge** [comment]
I think it's an Issue with the CMS. We should be passing the current menu selection on save to keep it, otherwise it's poor UX.

**Comment by zero-24** [comment]
So why do you open it against the code style repo? ;)

**Comment by tonypartridge** [comment]
Because I'm an idiot and had too many windows opens!

**Comment by zero-24** [comment]
Np :)
