### ISSUE TITLE
Errors on try/catch/finally

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#222]
Build: https://travis-ci.org/joomla-framework/console/jobs/331583389
Analyzed code: https://github.com/joomla-framework/console/blob/13a8498930831b88c5ece0327a1c46e331a54fb8/src/Application.php#L390-L466

**Comment by photodude** [comment]
This is a case to report to PHPCS as this is a failure in the sniff `Squiz.WhiteSpace.ControlStructureSpacing.NoLineAfterClose`

**Comment by photodude** [comment]
This has been addressed by PHPCS, but the fix might only be put in the 3.2.x master branch
https://github.com/squizlabs/PHP_CodeSniffer/issues/1890

We are quickly reaching a point where we need to finalize the PHPCS 2.x branch and move on to the PHPCS3.x branch as the PHPCS 2.9.x branch will somewhat shortly end bug fixes.

**Comment by photodude** [comment]
I've done the PR for the backport fix on this. 

The next release of PHPCS 2.9.x will be the last bug fix for that branch.

We can close this issue here.
