### ISSUE TITLE
[2.x] More Indention Issues With Closures

### ISSUE THREAD

**Issue by photodude** [joomla/coding-standards#230]
See https://travis-ci.org/joomla-framework/database/jobs/342589512#L1243-L1260 for reference

Seems #206 did not have enough test cases for #218 to completely solve the underlying issue. 

I tested a cutdown case of this issue https://github.com/photodude/coding-standards/blob/patch-2/Joomla/Tests/ControlStructures/ControlStructuresBracketsUnitTest.inc#L172-L202 

but I did not get an error. https://travis-ci.org/photodude/coding-standards/jobs/342585489#L544

I am unsure as to why the failure is occurring on the database package.

**Comment by photodude** [comment]
Looks like it is erroring
```sh
There was 1 failure:
1) Joomla_Tests_ControlStructures_ControlStructuresBracketsUnitTest::testSniff
[LINE 184] Expected 0 error(s) in ControlStructuresBracketsUnitTest.inc but found 1 error(s). The error(s) found were:
 -> Expected 4 tabs before opening brace; 3 found (Joomla.ControlStructures.ControlStructuresBrackets.SpaceBeforeBrace)
[LINE 189] Expected 0 error(s) in ControlStructuresBracketsUnitTest.inc but found 1 error(s). The error(s) found were:
 -> Expected 4 tabs before opening brace; 3 found (Joomla.ControlStructures.ControlStructuresBrackets.SpaceBeforeBrace)

Fixed version of ControlStructuresBracketsUnitTest.inc does not match expected version in ControlStructuresBracketsUnitTest.inc.fixed; the diff is
```

**Comment by wilsonge** [comment]
Closing in favour of PR in #242
