### ISSUE TITLE
[4.0] Anonymous class support

### ISSUE THREAD

**Issue by laoneo** [joomla/coding-standards#231]
In J4 the extension service providers are written as anonymous classes like here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/services/provider.php#L25

Currently CS fails on that with the following error:

FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
25 | ERROR | Missing class doc comment

But there is a class do block.

**Comment by photodude** [comment]
Should work with the 2.x and 3.x versions of the coding standard. With one current issue I have not been able to solve yet. See Issue #230 which shows the test case I found where the current fix from #218 didn't cover all cases.

**Comment by laoneo** [comment]
When are these standards used in drone for Joomla 4?

**Comment by photodude** [comment]
@laoneo the 3.x version is not yet used for testing J4. There are a few things needing to be cleaned up for getting the new versions in place. Read the last few comments in #143 for current progress

**Comment by laoneo** [comment]
Thanks. Should I close this issue?

**Comment by wilsonge** [comment]
Closing in favour of PR in #242
