### ISSUE TITLE
Analysis.md - 404 error on link from website

### ISSUE THREAD

**Issue by pvanbavel** [joomla/coding-standards#235]
On the `coding-standards.html` page off [Joomla! Developer Network™](https://developer.joomla.org/coding-standards.html) 
The link [tools available](https://developer.joomla.org/appendices/analysis.md) in  

> There are [tools available](https://developer.joomla.org/appendices/analysis.md) to help your code conform to our standards.

Generates a 404 error page. 
On Github the [correct page](https://github.com/joomla/coding-standards/blob/5263e4224ef9906eb88de3d571e478f97533670c/manual/appendices/analysis.md) is linked to.

**Comment by mbabker** [comment]
Known issue.  I need to get my hands on an updated version of the extension powering that section of the site to see if they've already tried to fix it, otherwise it'll either need a plugin or a component hack to parse links and fix them for display in that context.

**Comment by mbabker** [comment]
The component was changed a few weeks ago and the docs updated to link correctly on that site.
