### ISSUE TITLE
@since -> @SInCE

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/coding-standards#263]
On this page: 

https://developer.joomla.org/coding-standards/docblocks.html

All the `@since` tags are messed up and display as `@SInCE` even though the code here on GitHub is correct. 

<img width="133" alt="Screenshot 2020-07-02 at 18 35 54" src="https://user-images.githubusercontent.com/400092/86392161-e87d6300-bc92-11ea-8e38-fac6c5b43fb6.png">

**Comment by mbabker** [comment]
Not going to be fixed without changing the Markdown parser to anything but GitHub's API endpoint (which, may not be the worst of ideas in the long run; https://github.com/joomla/developer.joomla.org/tree/master/components/com_ghmarkdowndisplay is the component frontend code if someone has too much free time on their hands).
