### ISSUE TITLE
@headers link to invalid GitHub pages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/coding-standards#264]
All the `@` tags on this page https://developer.joomla.org/coding-standards/docblocks.html lead to invalid/unrelated GitHub.com/ pages. 

Eg:

@category goes to https://github.com/category

<img width="578" alt="Screenshot 2020-07-02 at 18 39 04" src="https://user-images.githubusercontent.com/400092/86392412-532e9e80-bc93-11ea-9a30-ae2c3a76a3df.png">

**Comment by mbabker** [comment]
I have no idea why the `@foo` stuff is getting converted to usernames when rendered through the API but not when displayed on the site, but wrapping all of the tags with backticks so they render as code elements would fix the issue in a roundabout way.
