### ISSUE TITLE
PHP_CodeSniffer 2.0 Compat

### ISSUE THREAD

**Issue by mbabker** [joomla/coding-standards#53]
PHP_CodeSniffer 2.0's [first alpha release](http://www.squizlabs.com/php-codesniffer/2.0.0a1-released/) has already shown some B/C breaks affecting our sniffs.  [This Travis build](https://travis-ci.org/joomla/joomla-framework/jobs/18487218) failed due to the comment parser classes being removed.  We'll need to look at this at some point, as well as other compatibility breaks.

**Comment by piotr-cz** [comment]
PHP_CodeSniffer 2.0 is stable now, latest version [is 2.1.0](https://github.com/squizlabs/PHP_CodeSniffer/releases).

**Comment by photodude** [comment]
[PHP_CodeSniffer 2.3.0 (stable)] (https://github.com/squizlabs/PHP_CodeSniffer/releases) was released on 2015-03-04 

It would be nice to see the comparability of Joomla Coding Standards Definition updated to the 2.x line now that there has been a couple of stable releases.

**Comment by photodude** [comment]
@mbabker do you think we could get a branch for developing a version of the coding-standards that works with PHP_CodeSniffer version 2.3.0?
I've started my own fork, for this development but I think it would be better if it was a branch in the main repo.

**Comment by mbabker** [comment]
There's now a `phpcs-2` branch in the repo.

**Comment by 886981109464** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/releases

**Comment by 886981109464** [comment]
https://github.com/photodude/coding-standards/tree/phpcs-2
