### ISSUE TITLE
Bootstrap styles conflict with Github syntax highlighting

### ISSUE THREAD

**Issue by nternetinspired** [joomla/coding-standards#59]
Syntax highlighting of html on github, as used at http://joomla.github.io/coding-standards/?coding-standards/chapters/html.md, adds a css class of close to the closing element.

Bootstrap uses this class to style alert closures. This causes the closing element to float right, appear like a link and be over-sized.

**Comment by photodude** [comment]
@mbabker this can be closed considering the elimination of the gh pages
