### ISSUE TITLE
Useless method overriding detected

### ISSUE THREAD

**Issue by bembelimen** [joomla/coding-standards#73]
source: Generic.CodeAnalysis.UselessOverridingMethod.Found

If you override a method and change only the parameters, the mentioned error appears. For example:

``` php
class A {
    public function Foo($bar = 1)
    { }
}

class B extends A {
    public function Foo($bar = 2)
    {
        parent::Foo($bar);
    }
}
```

I think that should be fixed for Joomla!

**Comment by mbabker** [comment]
FWIW this has been a problem when running PHPCS on some of our Framework repos and looks to be fixed with the 2.0 ruleset.  So I'm going to consider this closed.
