### ISSUE TITLE
Changes in the tag requirements

### ISSUE THREAD

**Issue by javigomez** [joomla/coding-standards#80]
I'm pasting this message here so we all are aware:

Michael Babker
Sep 23 

to Production Leadership Team
I regenerated the docs for api.joomla.org as part of my release execution and the current version of phpDocumentor is throwing new errors on having multiple `@package` tags in a file.  In the CMS, we currently place `@package` and `@subpackage` tags in both the file and class doc block, and those are duplicated lines of information that aren't necessary in both doc blocks.  As the CMS classes are not namespaced, the use of `@package` and `@subpackage` is required to group our code into appropriate packages.  Namespaced code (like the Framework) uses the namespace as the grouping.

Given that phpDocumentor is now throwing errors over our duplicated tags, and them not being a true requirement in multiple doc blocks, would it be an issue to make the `@package` and `@subpackage` tags not required in the CMS codestyle sniffs for class doc blocks (a change that is consistent with the sniffs in the main coding-standards repo) and allow folks to remove these tags from class doc blocks?

![screen shot 2014-09-23 at 17 34 24](https://cloud.githubusercontent.com/assets/1375475/4408218/56422730-44d1-11e4-8339-9f712b3d5bb8.png)

The `@package` and `@subpackage` tags would be not required in class doc blocks but would still be required in the file doc block, as it is today.  Those tags typically aren't used in method doc blocks or inline style doc blocks.

No other changes are being proposed right now.

**Comment by photodude** [comment]
I think this is addressed in the PHPCS-2 version of the rules which ignores the package tag requirement on namespaced code.
