### ISSUE TITLE
Is 150 characters maybe to few

### ISSUE THREAD

**Issue by javigomez** [joomla/coding-standards#84]
Originally the reason for having 150 chars was to be able to print the code so it fits in one page. But I don't think no one prints code today.

Of course is not nice to have looooooong lines, but there are cases like when you add default values to the params of a function where  I think we should be more flexible giving more than 150 chars:

![screen shot 2014-10-09 at 13 21 25](https://cloud.githubusercontent.com/assets/1375475/4575354/1b0d9a70-4fa6-11e4-880d-82bd7c953562.png)

What do you think?

**Comment by photodude** [comment]
I agree with @elkuku "horizontal scrolling is one thing we should avoid" 
I would vote to leave at 150 or change to 120 to match the PHPCS default rule.

**Comment by javigomez** [comment]
agreed :+1: 

Closing this issue.
