### ISSUE TITLE
Move all Platform @since version numbers into Joomla version numbers

### ISSUE THREAD

**Issue by javigomez** [joomla/coding-standards#85]
We have several @since tags in the code, something like:

```
/**
 * HTTP response data object class.
 *
 * @since       XX.X
 */
```

Some of that @since tags are showing Platform numbers. Instead we should change them for the corresponding Joomla version at that time. So for example https://github.com/joomla/joomla-cms/blob/ea05ad099fca9325d5d9e15d0f2bf34be0cb90c8/libraries/joomla/http/response.php#L17 says 11.4 meaning the Joomla Platform 11.4 that was released on February 2013 http://developer.joomla.org/news/20-version-11-4-of-the-joomla-platform-released.html 

We should change it for the next stable version of Joomla that was released after February 2013. If we check the Joomla version history: http://docs.joomla.org/Joomla_2.5_version_history we found that after February 2013 was released Joomla! 2.5.10 (24 April 2013)

So this line https://github.com/joomla/joomla-cms/blob/ea05ad099fca9325d5d9e15d0f2bf34be0cb90c8/libraries/joomla/http/response.php#L17 should be switched to 2.5.10

We need to switch all tags @since from platform version numbers into joomla version numbers

**Comment by photodude** [comment]
Close and reopen in the cms repo or just close as extra work with little benefit?

**Comment by mbabker** [comment]
If someone wants to do it then go for it.  It'd probably be better to do it to avoid version number confusion.
